export const content = [
  {
    content_id: 1,
    keywords: "technology, innovation, gadgets",
    ptitle: "The Future of Technology",
    pcontent:
      "Technology is evolving at an unprecedented pace, with innovations transforming industries and daily life.",
    pbanner: 101,
    categoryid: 5,
    datecreated: "2024-08-01T10:15:30Z",
    lastmodified: "2024-08-15T14:30:00Z",
    ispublished: "yes",
    url: "New Tab/Window",
    source: "Tech Daily",
    directlink: "https://www.techdaily.com/future-of-technology",
    extracode: "<script>alert('Welcome to Tech Daily');</script>",
    pagehits: 150,
    cattype: "page",
  },
  {
    content_id: 2,
    keywords: "health, wellness, fitness",
    ptitle: "10 Tips for a Healthier Lifestyle",
    pcontent:
      "Discover easy and effective tips to improve your health and well-being.",
    pbanner: 102,
    categoryid: 3,
    datecreated: "2024-07-25T08:00:00Z",
    lastmodified: "2024-08-18T16:00:00Z",
    ispublished: "yes",
    url: "Same Tab/Window",
    source: "Health Hub",
    directlink: "https://www.healthhub.com/healthier-lifestyle-tips",
    extracode: "<script>alert('Stay Healthy');</script>",
    pagehits: 200,
    cattype: "cat",
  },
  {
    content_id: 3,
    keywords: "travel, adventure, destinations",
    ptitle: "Top 10 Travel Destinations for 2024",
    pcontent: "Explore the most exciting travel destinations to visit in 2024.",
    pbanner: 103,
    categoryid: 7,
    datecreated: "2024-08-05T12:45:00Z",
    lastmodified: "2024-08-20T11:00:00Z",
    ispublished: "yes",
    url: "New Tab/Window",
    source: "Travel World",
    directlink: "https://www.travelworld.com/top-10-destinations-2024",
    extracode: "<script>alert('Bon Voyage');</script>",
    pagehits: 175,
    cattype: "page",
  },
  {
    content_id: 4,
    keywords: "finance, investing, stocks",
    ptitle: "How to Invest in the Stock Market",
    pcontent:
      "A beginner's guide to investing in the stock market and building wealth.",
    pbanner: 104,
    categoryid: 2,
    datecreated: "2024-07-20T14:00:00Z",
    lastmodified: "2024-08-19T09:30:00Z",
    ispublished: "yes",
    url: "Same Tab/Window",
    source: "Finance Today",
    directlink: "https://www.financetoday.com/investing-in-stocks",
    extracode: "<script>alert('Invest Wisely');</script>",
    pagehits: 220,
    cattype: "cat",
  },
  {
    content_id: 5,
    keywords: "cooking, recipes, food",
    ptitle: "5 Easy Dinner Recipes for Busy Weeknights",
    pcontent:
      "Quick and delicious dinner recipes that you can make in under 30 minutes.",
    pbanner: 105,
    categoryid: 6,
    datecreated: "2024-08-10T18:30:00Z",
    lastmodified: "2024-08-21T13:15:00Z",
    ispublished: "yes",
    url: "New Tab/Window",
    source: "Cooking Corner",
    directlink: "https://www.cookingcorner.com/easy-dinner-recipes",
    extracode: "<script>alert('Bon Appétit');</script>",
    pagehits: 185,
    cattype: "page",
  },
  {
    content_id: 6,
    keywords: "education, online learning, courses",
    ptitle: "Top Online Courses to Boost Your Career",
    pcontent:
      "Enhance your skills and advance your career with these top online courses.",
    pbanner: 106,
    categoryid: 8,
    datecreated: "2024-07-15T09:00:00Z",
    lastmodified: "2024-08-17T17:45:00Z",
    ispublished: "yes",
    url: "Same Tab/Window",
    source: "Edu World",
    directlink: "https://www.eduworld.com/top-online-courses",
    extracode: "<script>alert('Learn More');</script>",
    pagehits: 250,
    cattype: "cat",
  },
  {
    content_id: 7,
    keywords: "sports, football, world cup",
    ptitle: "World Cup 2024: What to Expect",
    pcontent:
      "Get ready for the biggest football event of the year with this comprehensive guide.",
    pbanner: 107,
    categoryid: 4,
    datecreated: "2024-08-01T07:15:00Z",
    lastmodified: "2024-08-20T10:30:00Z",
    ispublished: "yes",
    url: "New Tab/Window",
    source: "Sports Arena",
    directlink: "https://www.sportsarena.com/world-cup-2024-guide",
    extracode: "<script>alert('Go Team');</script>",
    pagehits: 300,
    cattype: "page",
  },
  {
    content_id: 8,
    keywords: "movies, entertainment, reviews",
    ptitle: "Top 10 Movies to Watch in 2024",
    pcontent:
      "From action-packed blockbusters to heartfelt dramas, these are the must-see movies of 2024.",
    pbanner: 108,
    categoryid: 9,
    datecreated: "2024-07-28T20:00:00Z",
    lastmodified: "2024-08-18T12:00:00Z",
    ispublished: "yes",
    url: "Same Tab/Window",
    source: "Movie Buff",
    directlink: "https://www.moviebuff.com/top-10-movies-2024",
    extracode: "<script>alert('Movie Time');</script>",
    pagehits: 275,
    cattype: "cat",
  },
  {
    content_id: 9,
    keywords: "fashion, style, trends",
    ptitle: "2024 Fashion Trends You Need to Know",
    pcontent:
      "Stay ahead of the curve with the latest fashion trends for 2024.",
    pbanner: 109,
    categoryid: 1,
    datecreated: "2024-07-22T15:45:00Z",
    lastmodified: "2024-08-19T15:00:00Z",
    ispublished: "yes",
    url: "New Tab/Window",
    source: "Style Guide",
    directlink: "https://www.styleguide.com/2024-fashion-trends",
    extracode: "<script>alert('Stay Stylish');</script>",
    pagehits: 325,
    cattype: "page",
  },
  {
    content_id: 10,
    keywords: "science, space, exploration",
    ptitle: "The Future of Space Exploration",
    pcontent:
      "Space agencies around the world are planning missions that will take us further into the cosmos.",
    pbanner: 110,
    categoryid: 10,
    datecreated: "2024-08-12T11:30:00Z",
    lastmodified: "2024-08-20T18:15:00Z",
    ispublished: "yes",
    url: "Same Tab/Window",
    source: "Science Today",
    directlink: "https://www.sciencetoday.com/space-exploration-future",
    extracode: "<script>alert('To Infinity and Beyond');</script>",
    pagehits: 400,
    cattype: "cat",
  },
];
